### PR TITLE
Update UI

### LINKED ISSUE #48: UI doesn't react well with global scaling
I'm running Manjaro with KDE Plasma. I have set global scaling to be at 125%. The UI now looks like this:

Main window:
grafik

Settings page:
grafik

It still works as expected, but doesn't look so good. Also, with more plugins in the settings page, I think this will get even worse. The wallpaper setting is already pretty small and parts of the version info are cropped.

### PR DESCRIPTION
**Pull request by l0drex**
- I deleted unneeded or duplicated files
- I moved the application logic outside the UI. The UI is now responsible only for changing settings (and manual change), after the application closes the thread is started.
- I gave the centralWidget a layout, so that every widget is now positioned and scaled automatically
- depending on the desktop in the config, some plugins get disabled and you can not enable them (for example, I use KDE and therefore Gnome is disabled). It would also be possible to make the widget invisible :thinking: 

I tested if every setting in the UI changes the config properly, if I missed something let me know :sweat_smile: 

Fixes #48

### CODE REVIEW

**Comment by l0drex** [comment]
Here is how it looks now:
main window settings

**Comment by l0drex** [comment]
# An alternative  design for the main window

schedule sun

- unselected options are hidden, I could even put the buttons in an additional option "manual"
- the selected mode could be set directly in the config, possibly with an enum containing all the options rather than using boolean for every option
- the times for sunrise and sunset are not visible anymore, but I could add a label for that

**Comment by daehruoydeef** [comment]
Hey this is looking really good!

**Comment by neo14515** [comment]
Hello,
I think this version (https://github.com/daehruoydeef/Yin-Yang/pull/68#issuecomment-711203843) works better from a UX perspective as it doesn't hide the options behind a drop-down. I would also recommend to align the check-boxes to the left instead of having them centred. Finally what about a toggle instead of a check box for the different desktop options?
Cheers,

**Comment by l0drex** [comment]
> I think this version ([#68 (comment)](https://github.com/daehruoydeef/Yin-Yang/pull/68#issuecomment-711203843)) works better from a UX perspective as it doesn't hide the options behind a drop-down

I agree, if sunrise and sunset are used as the time, the user should see which time has been set. Same for the position if there's a feature in the future which sets the location based on the current position.


> I would also recommend to align the check-boxes to the left instead of having them centred

I'm using `title` and `checkable` properties of [QGroupBox](https://doc.qt.io/qt-5/qgroupbox.html). The title is actually set to be left, hover it seems like not every theme supports it. The windows and fusion theme seem to align it properly.
A workaround would be to add a checkbox manually, but this would make things more complicated.


> Finally what about a toggle instead of a check box for the different desktop options?

As far as I know there is no toggle in Qt.

**Comment by l0drex** [comment]
I'm also thinking about adding a small icon in the notification center which can be used to toggle the theme manually. Depending on the theme in use, the icon would switch to a dark or bright version. With a right click, the user could open the settings menu.

Also, an option to send a notification about theme changes would be nice.

**Comment by neo14515** [comment]
Hello,

I found these resources about toggle button in Qt:
https://stackoverflow.com/questions/14780517/toggle-switch-in-qt
https://doc.qt.io/qt-5/qmlexampletoggleswitch.html
I don't know if it's helpful but in the stackoverflow there is even a python implementation example ;-) 

As for the small icon I think that it would be a nice addition. In KDE they do have one for Night Color that you can probably check as example.

Cheers,

**Comment by daehruoydeef** [comment]
I would not let the user fill in there own lat / long. You should be able to switch between time and sunrise/ sunset. Both options exposing the  fields to adjust the time. The difference is that with the lat / long the fields are locked and the values are pre filled.
Also it should be sunrise to sunset. 
I will come up with a variation of this Design, I will hide the Play Sound behind the Settings leaving the main interface as clean as possible. Also the Settings Button will get a actual Settings Icon.

I am happy to announce that I can continue working on this project now and dedicate more time. Thank you for your help, I really appreciate that!

**Comment by daehruoydeef** [comment]
Also I see that the new UI features a tab called applications, with the current implementation this is not possible it would need to alter the windows rules. Right now the best effort would be to enhance stability, come up with a real installation process and enhance the GTK Support. 
I did a V2 branch, there is a slightly new GUI that is conditional based on the desktop environment you are using. Gnome is exposing different fields than on KDE. I would like to keep this tool as much cross platform as possible. Using a notification icon would be a really great idea for KDE but would need to be disabled on Gnome or other. Also lets keep the checkbox as a toggle switch. We would need to do our own implementation for this which is not worth it I think

**Pull request closed without merging**
